version: "3"

services:
  web:
    container_name: Ezequiel
    restart: always
    build: .
    ports:
      - "4000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
        
  mongo:
    container_name: db_mongo
    image: mongo
    ports:
      - "27017:27017"
